### ISSUE TITLE
Spaced Pathnames still failing (version 1.1.4)

### ISSUE THREAD

**Issue by JelaMiraj** [alexeyvax/vscode-open-native-terminal#2]
Thank you so much for trying to fix the pathnames with spaces failing bug, but it is somehow still there in version 1.1.4.
I keep my code in Google Drive so my latest work is still backed up in between commits.

**Comment by alexeyvax** [comment]
Hi Jamamuuga, I need more information about your OS and this bug. Could you please describe in more detail? This case happens all the time or once? Thanks.

**Comment by jpsheehan** [comment]
Hi, same issue here. It's failing to open a terminal within my repo folder. The error occurs when I click open root folder or current folder. I do have a space in my windows username which is why I believe it is failing. My default terminal is cmd.exe

Extension information:
  1.3.0 2018-09-23

VSCode information:
  Version: 1.28.2 (user setup)
  Commit: 7f3ce96ff4729c91352ae6def877e59c561f4850
  Date: 2018-10-17T00:23:51.859Z
  Electron: 2.0.9
  Chrome: 61.0.3163.100
  Node.js: 8.9.3
  V8: 6.1.534.41
  Architecture: x64

Error message is:
  "Windows cannot find 'MYLASTNAME\source\repos\REPONAME'. Make sure you've typed the name correctly then try again."

**Comment by alexeyvax** [comment]
Hi @jpsheehan,
Thank you for your info about this issue!
I'm going to investigate and after that fix this issue. I think it takes about 2 days.

**Comment by alexeyvax** [comment]
Hi @Jamamuuga and @jpsheehan after investigation this issue I found the bug.
This bug has been fixed in the 1.4.0 version. This version is available for usage. So please update this extension to latest version. And also could you please let me know if 1.4.0 version works for you.

**Comment by jpsheehan** [comment]
Thanks for the bug fix there @alexeyvax. The "Open in native terminal (current folder)" function works a treat. However, the "Open in native terminal (root folder)" function still has the same issue as before. I can use the "current folder" option in the root folder to open the root folder if I want to, that seems to work.

I believe that line 85 of 'src/utils/index.ts' should read:
```typescript
return getCorrectPath(vscode.workspace.workspaceFolders[0].uri.fsPath);
```

**Comment by alexeyvax** [comment]
Yes, @jpsheehan you are right! I've fixed this issue for root folder on the 1.4.2 version. This version have already available for usage. Could you please take a look at it and send me feedback? Thanks.

**Comment by jpsheehan** [comment]
Yep @alexeyvax that fixed it, it's now working perfectly! Thanks for updating the extension. Have a great day.

**Comment by alexeyvax** [comment]
@jpsheehan thank you for your support, and have a great day too! :)
